name: Build
run-name: ${{ github.actor }} is Building 🚀
on: [push]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-osx:
    name: Build for OSX
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Projucer
        run: cd JUCE/extras/Projucer/Builds/MacOSX && xcodebuild -configuration Release
      - name: Move Projucer
        run: mv JUCE/extras/Projucer/Builds/MacOSX/build/Projucer ./JUCE/Projucer
      - name: Generate Builds (resave)
        run: ./JUCE/Projucer.app/Contents/MacOS/Projucer --resave FirmwareSender.jucer
      - name: Build
        run: cd Builds/MacOSX && xcodebuild -configuration Release
      - name: Zip
        run: cd Builds/MacOSX/build/Release && zip FirmwareSender-osx.zip FirmwareSender
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: Builds/MacOSX/build/Release/FirmwareSender-osx.zip


  build-ubuntu:
    name: Build for Ubuntu
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install -y libasound2-dev libjack-jackd2-dev libcurl4-openssl-dev
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Projucer
        run: cd JUCE/extras/Projucer/Builds/LinuxMakefile && make -j
      - name: Move Projucer
        run: mv JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer ./JUCE/Projucer
      - name: Generate Builds (resave)
        run: ./JUCE/Projucer --resave FirmwareSender.jucer
      - name: Build
        run: cd Builds/LinuxMakefile && make -j
      - name: Zip
        run: cd Builds/LinuxMakefile/build && zip FirmwareSender-ubuntu.zip FirmwareSender
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: Builds/LinuxMakefile/build/FirmwareSender-ubuntu.zip


  build-windows:
    name: Build for Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build Projucer
        run: cd JUCE/extras/Projucer/Builds/VisualStudio2022 && msbuild Projucer_App.vcxproj /p:configuration=release /p:platform=x64
      - name: Move Projucer
        run: mv JUCE/extras/Projucer/Builds/VisualStudio2022/build/Projucer.exe ./JUCE/Projucer.exe
      - name: Generate Builds (resave)
        run: JUCE/Projucer.exe --resave FirmwareSender.jucer
      - name: Build
        run: cd Builds/VisualStudio2022 && msbuild FirmwareSender_ConsoleApp.vcxproj /p:configuration=release /p:platform=x64
      - name: Zip
        run: cd Builds/VisualStudio2022/x64/release/ConsoleApp && Compress-Archive FirmwareSender.exe FirmwareSender-windows.zip
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: Builds/VisualStudio2022/x64/release/ConsoleApp/FirmwareSender-windows.zip
